create extension if not exists "pgcrypto";

create table if not exists agents (
        id uuid primary key default gen_random_uuid(),
        external_id bigint generated by default as identity unique,
        name text not null,
        token_hash text not null,
        location text,
        version text,
        agent_ip inet,
        max_parallel int not null default 4,
        last_seen timestamptz,
        is_active boolean not null default true,
        created_at timestamptz not null default now()
);

alter table agents add column if not exists external_id bigint generated by default as identity;
update agents set external_id = nextval(pg_get_serial_sequence('agents','external_id')) where external_id is null;
create unique index if not exists idx_agents_external_id on agents(external_id);
create index if not exists idx_agents_last_seen on agents(last_seen);
