create table if not exists leases (
        id uuid primary key default gen_random_uuid(),
        external_id bigint generated by default as identity unique,
        agent_id uuid not null references agents(id) on delete cascade,
        check_id uuid not null,
        task_id uuid not null,
        kind text not null,
        spec jsonb not null,
        stream_id text not null,
        leased_until timestamptz not null,
        retry_count int not null default 0,
        created_at timestamptz not null default now()
);

alter table leases add column if not exists external_id bigint generated by default as identity;
update leases set external_id = nextval(pg_get_serial_sequence('leases','external_id')) where external_id is null;
create unique index if not exists idx_leases_external_id on leases(external_id);
create index if not exists idx_leases_agent on leases(agent_id);
create index if not exists idx_leases_check on leases(check_id);
create index if not exists idx_leases_leased_until on leases(leased_until);
