---
# Variables specific to the auth-svc deployment

go_app_service_name: auth-svc
go_app_src_dir: /srv/aezacheck/auth-svc
go_app_binary_name: auth-svc

go_app_env_map:
  APP_URL: https://auth.aezacheck.internal
  JWT_SECRET: "{{ secrets.jwt_signing_key }}"
  REDIS_URL: "redis://:{{ REDIS_PASSWORD }}@{{ REDIS_HOST }}:{{ REDIS_PORT }}/0"
  GEOIP_ENDPOINT: https://geoip.aezacheck.internal
  LOG_LEVEL: info

go_app_exec_args:
  - serve
  - --config
  - "{{ go_app_config_path }}"

go_app_migrate_command: "{{ go_app_release_dir }}/{{ go_app_binary_name }} migrate --config {{ go_app_config_path }}"

go_app_memory_limit: "{{ performance.go_app_memory_default }}"
go_app_cpu_quota: "{{ performance.go_app_cpu_quota_default }}"

go_app_database_name: auth_db
go_app_pg_owner: postgres

go_app_systemd_extra:
  Environment: SERVICE_NAME=auth-svc
