all:
  children:
    database:
      hosts:
        postgres:
    cache:
      hosts:
        redis:
    auth_svc:
      hosts:
        auth01:
    sites_svc:
      hosts:
        sites01:
    jobs_svc:
      hosts:
        jobs01:
