---
# Variables specific to the api-gw deployment

go_app_service_name: api-gw
go_app_src_dir: /srv/aezacheck/api-gw
go_app_binary_name: api-gw
go_app_env_file: "{{ go_app_release_dir }}/.env.gateway"
go_app_env_map:
  HTTP_ADDR: ":8088"
  AUTH_BASE_URL: http://auth-svc:8080
  SITES_BASE_URL: http://sites-svc:8081
  JOBS_BASE_URL: http://jobs-svc:8082
  JWT_SECRET: "changeme-gateway"
  JWT_AUDIENCE: aezacheck
  JWT_ISSUER: auth-svc
  CORS_ALLOWED_ORIGINS: "*"
  RATE_ENABLED: "1"
  RATE_RPS: "5"
  RATE_BURST: "10"
  RATE_SKIP_AGENTS: "1"
  BASIC_TO_JWT_ENABLED: "1"
  LOGIN_TIMEOUT_SEC: "5"
go_app_exec_args: []
go_app_migrate_command: ""
go_app_unit_after:
  - network.target
  - auth-svc.service
  - sites-svc.service
  - jobs-svc.service
go_app_unit_wants:
  - auth-svc.service
  - sites-svc.service
  - jobs-svc.service
go_app_limit_nofile: 65535
go_app_systemd_extra:
  Environment: SERVICE_NAME=api-gw
