all:
  children:
    production:
      vars:
        ansible_user: deploy
      children:
        database:
          hosts:
            postgres-prod-01:
              ansible_host: 10.20.0.10
        cache:
          hosts:
            redis-prod-01:
              ansible_host: 10.20.0.11
        auth_svc:
          hosts:
            auth-prod-01:
              ansible_host: 10.20.1.10
        sites_svc:
          hosts:
            sites-prod-01:
              ansible_host: 10.20.1.20
        jobs_svc:
          hosts:
            jobs-prod-01:
              ansible_host: 10.20.1.30
        api_gw:
          hosts:
            api-gw-prod-01:
              ansible_host: 10.20.2.10
        dns_agents:
          hosts:
            dns-agent-prod-01:
              ansible_host: 10.20.3.10
            dns-agent-prod-02:
              ansible_host: 10.20.3.11
