---
galaxy_info:
  role_name: redis
  author: dns-server maintainers
  description: Install and configure Redis for aezacheck services.
  company: aezacheck
  license: MIT
  min_ansible_version: '2.12'
  platforms:
    - name: Debian
      versions: ['bullseye', 'bookworm']
    - name: Ubuntu
      versions: ['focal', 'jammy']
dependencies: []
