all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
      ansible_become: false
  children:
    database:
      hosts:
        localhost:
    cache:
      hosts:
        localhost:
    auth_svc:
      hosts:
        localhost:
    sites_svc:
      hosts:
        localhost:
    jobs_svc:
      hosts:
        localhost:
    api_gw:
      hosts:
        localhost:
    dns_agents:
      hosts:
        localhost:
