redis_packages:
  - redis-server
redis_service_name: redis-server
redis_conf_path: /etc/redis/redis.conf
redis_data_dir: /var/lib/redis
redis_bind_address: 0.0.0.0
redis_port: "{{ REDIS_PORT | default(6379) }}"
redis_password: "{{ REDIS_PASSWORD | default('') }}"
redis_appendonly: 'yes'
